name: CD Infra

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_PUBLIC_IP }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.RSA_VM_KEY }}
          script: |
            cd ~/infra
            git switch dev
            git pull
            ./start-docker.sh

      - name: Deploy Prod
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_PROD_PUBLIC_IP }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.RSA_VM_KEY }}
          script: |
            cd ~/infra
            git switch main
            git pull
            ./start-docker.sh
