name: CD Infra

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_PUBLIC_IP_DEV }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.RSA_VM_KEY }}
          script: |
            cd ~/infra
            sudo git pull
            ./start-docker.sh
      - name: Deploy to Main VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_PUBLIC_IP_MAIN }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.RSA_VM_KEY }}
          script: |
            cd ~/infra
            sudo git pull
            ./start-docker.sh
